spring:
  application:
    name: apigateway
  cloud:
    gateway:
      routes: 
        - id: information-service
          uri: lb://information
          predicates:
            - Path=/chatcofrade/informacion/**
        - id: ai-models
          uri: lb://AImodels
          predicates:
          - Path=/chatcofrade/ai/**
  
server:
  port: 8080

logging:
  level:
    root: INFO
    '[org.springframework.cloud.gateway]': TRACE
    '[org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator]': INFO

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:password@localhost:8761/eureka
