vaadin:
  launch-browser: true

spring:
  application:
    name: backoffice
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: cofrade-gpt
            client-secret: GENGXarFH1titMk52zZZyawK8bJUzRiU
            scope: profile,openid,email,roles
            provider: keycloak

          vaadin-m2m:
            client-id: vaadin-backoffice-m2m
            client-secret: fMhcA1L100TFUZEjNuyLNtePzdOFJAK9
            authorization-grant-type: client_credentials
            provider: keycloak
        provider:
          keycloak:
            issuer-uri: http://localhost:8181/realms/CofradeGPT

server:
  port: 8085

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:password@localhost:8761/eureka

